import type { EducationalModule } from "@/lib/schemas";

export const educationalModuleRecords = [
  {
    slug: "model-lifecycle",
    title: "From pretraining to agents: how the AI model-development lifecycle fits together",
    summary: "A system-level guide to how base models become instruction-following, evaluated, tool-using systems—and how evidence from operation feeds the next cycle.",
    order: 1,
    glossaryTerms: [
      "pretraining",
      "post-training",
      "supervised-fine-tuning",
      "data-annotation",
      "preference-data",
      "rlhf",
      "reward-model",
      "reinforcement-learning",
      "benchmark",
      "evaluation",
      "synthetic-data",
      "agent-environment",
      "inference",
    ],
    relatedCompanies: ["mercor", "afterquery", "fleet"],
    sections: [
      {
        id: "learning-objective",
        type: "paragraph",
        heading: "Learning objective: follow capability through the system",
        body: "By the end of this module, you should be able to distinguish pretraining, post-training, evaluation, and inference; explain how an agent operates across tools and environments; and trace how evidence from failures becomes new data or tests. The sequence is an explanatory model, not a universal recipe: teams often create data, train, evaluate, and operate systems in overlapping feedback loops.",
      },
      {
        id: "system-map",
        type: "paragraph",
        heading: "System map: one loop, not four silos",
        body: "At the broadest level, pretraining builds a base model; post-training shapes its behavior; evaluation measures capabilities and failures; and inference or deployment exposes the resulting system to new tasks. Findings from evaluation, simulations, and real operation then feed back into data creation, task design, training, and the next evaluation cycle.",
      },
      {
        id: "pretraining",
        type: "stage",
        name: "01 · Pretraining builds a base model",
        summary: "Pretraining uses large, varied datasets and a predictive objective—such as predicting the next token in a sequence—to build reusable representations and broad capabilities. The resulting base model can transfer to many tasks, but pretraining alone does not guarantee reliable instruction following, factuality, safety, or task-specific performance. Post-training shapes that behavior, while evaluation tests what the model can do and where it fails.",
        inputs: [
          "Large collections of text, code, images, audio, or other modalities",
          "A predictive objective, such as next-token prediction",
          "A model architecture and optimization process",
        ],
        outputs: [
          "A base model with broad learned representations and capabilities",
          "A starting point for post-training and evaluation—not a finished assistant or agent",
        ],
        sourceIds: ["gpt3-few-shot-learners", "foundation-models-report"],
      },
      {
        id: "post-training",
        type: "stage",
        name: "02 · Post-training shapes behavior",
        summary: "Post-training adapts a base model toward desired tasks and behavior. Demonstrations used in supervised fine-tuning teach by example. Preference data records which outputs are better: reinforcement learning from human feedback (RLHF) commonly learns a reward model and optimizes against it, while direct preference optimization (DPO) learns directly from preference pairs. Reinforcement learning with verifiable rewards (RLVR) instead uses outcomes that can be checked, such as an exact answer or passing tests. Interactive environments add multi-step practice. These signals can be combined, but they are not interchangeable.",
        inputs: [
          "Expert demonstrations and supervised fine-tuning examples",
          "Preference comparisons, rankings, and rubrics",
          "Verifiable outcomes, such as exact answers or passing tests",
          "Tasks and environments for multi-step practice",
        ],
        outputs: [
          "Instruction-following and task behavior learned from examples",
          "Behavior optimized toward stated preferences or checkable outcomes",
          "A model prepared for evaluation and, where relevant, tool-using operation",
        ],
        sourceIds: ["instructgpt-human-feedback", "direct-preference-optimization", "tulu-3-post-training"],
      },
      {
        id: "evaluation",
        type: "stage",
        name: "03 · Evaluation closes the loop",
        summary: "Evaluation asks whether a model or agent performs the intended task, under which conditions, and with what failures. Evaluation sets and benchmarks standardize tasks; rubrics define what good performance means; automated checks and model-based graders add scale; and human review supplies context and judgment. Failure analysis matters as much as a score. Benchmark contamination can make a test less informative when its tasks or close variants appear in training data, while one aggregate score can hide trade-offs across scenarios, metrics, and user groups.",
        inputs: [
          "Held-out evaluation sets, benchmarks, and realistic task suites",
          "Rubrics, automated checks, model-based graders, and human reviewers",
          "Logs and trajectories from simulated or deployed operation",
        ],
        outputs: [
          "Scores plus qualitative evidence about strengths and failure modes",
          "Release decisions and limitations stated with appropriate caveats",
          "New priorities for data creation, training, and evaluation design",
        ],
        sourceIds: ["tulu-3-post-training", "helm-evaluation", "llm-as-a-judge"],
      },
      {
        id: "inference-and-agents",
        type: "stage",
        name: "04 · Inference becomes agent operation",
        summary: "Inference runs a trained model on new input. A tool-using agent wraps that model in a larger operational system: instructions define the task; tools enable actions; state or memory carries information forward; an environment returns observations; and evaluation and feedback judge outcomes. A trajectory is the sequence of observations, decisions, tool calls, and results produced along the way. Computer-use agents may operate browsers, terminals, or graphical interfaces. An agent is therefore not a clean fifth training stage—it is a system whose operation can generate evidence for later training and evaluation.",
        inputs: [
          "A trained model, task instructions, and relevant context",
          "Tools such as search, code execution, APIs, browsers, or computer controls",
          "State or memory plus an environment that responds to actions",
        ],
        outputs: [
          "Answers, actions, and multi-step trajectories",
          "Outcome checks, human feedback, and operational observations",
          "Failure cases that can become new evaluation or training data",
        ],
        sourceIds: ["react-reasoning-acting", "webarena-agent-environment"],
      },
      {
        id: "worked-example",
        type: "callout",
        title: "Worked example: a software-research agent",
        body: "This is an illustrative synthesis, not the documented pipeline of a particular company. First, a base model learns broad language and code patterns during pretraining. Experts then demonstrate how to inspect a repository, plan a change, use a terminal, and explain evidence; supervised fine-tuning teaches those task patterns. Preference judgments can distinguish clearer or safer approaches, while checkable outcomes such as passing tests can provide a verifiable reward. In a sandboxed agent environment, the system practices multi-step work and records trajectories. Held-out tasks, rubrics, automated tests, model graders, and human review evaluate the result. During inference, the agent receives a new issue, searches code, edits files, runs tests, and reports its reasoning. Failure analysis may reveal that it ignored a dependency or overfit to familiar tests; reviewers can turn that failure into a new demonstration, environment task, or evaluation case for the next cycle.",
      },
      {
        id: "industry-fit",
        type: "paragraph",
        heading: "Where the current industry categories fit",
        body: "Expert data platforms can organize demonstrations, preferences, rubrics, and domain review. RL environment providers can build interactive worlds where agents practice and are evaluated. Evaluation platforms can supply benchmarks, graders, and failure analysis. Specialized data providers can collect or generate modality-, domain-, or task-specific material. Mercor, AfterQuery, and Fleet illustrate overlapping roles across these activities; the four active Version 1 categories are navigation aids, not permanent boundaries, rankings, or claims that every company belongs to only one stage.",
      },
      {
        id: "feedback-loop",
        type: "callout",
        title: "The lifecycle is governed by feedback, not handoffs",
        body: "A stronger evaluation can change what a team trains next. A failure in a benchmark, sandbox, or deployed workflow may motivate a new rubric, a harder environment task, a targeted demonstration, or a different reward signal. The same evidence can also show that more training is not the answer—for example, when the real problem is an unreliable tool, ambiguous instruction, or poorly specified success criterion.",
      },
      {
        id: "evaluation-limitations",
        type: "details",
        title: "Evaluation limits: contamination, graders, and aggregate scores",
        body: "Benchmark contamination occurs when evaluation tasks or close variants enter training data, weakening the test as evidence of generalization. Aggregate scores can conceal important differences between scenarios and metrics. Model-based graders can scale open-ended evaluation, but they may show position, verbosity, self-preference, or reasoning biases, so teams still need calibrated rubrics, automated checks where possible, and selective human review. Passing one benchmark does not guarantee dependable operation outside its tested conditions.",
        sourceIds: ["tulu-3-post-training", "helm-evaluation", "llm-as-a-judge"],
      },
      {
        id: "training-signal-limitations",
        type: "details",
        title: "Training-signal limits: gaming, synthetic data, and distribution shift",
        body: "Reward hacking or specification gaming occurs when a system finds a way to score well without accomplishing the intended goal. Synthetic data can target scarce or difficult cases, but generated errors, narrowness, and repetition still require review. Distribution shift appears when real inputs or environments differ from those used in training and evaluation. These limits are why post-training signals need continuing evaluation—and why better evaluation can redirect data and training priorities rather than merely produce a higher score.",
        sourceIds: ["foundation-models-report", "concrete-ai-safety-problems"],
      },
      {
        id: "continue-exploring",
        type: "paragraph",
        heading: "Continue exploring",
        body: "Use the connected glossary to open individual methods, the company profiles to see how current providers describe their work, the ecosystem categories to navigate the active Version 1 landscape, and the bibliography to inspect the direct evidence behind this synthesis.",
      },
    ],
    sourceIds: [
      "gpt3-few-shot-learners",
      "foundation-models-report",
      "instructgpt-human-feedback",
      "direct-preference-optimization",
      "tulu-3-post-training",
      "helm-evaluation",
      "llm-as-a-judge",
      "react-reasoning-acting",
      "webarena-agent-environment",
      "concrete-ai-safety-problems",
    ],
    lastReviewed: "2026-07-13",
  },
] satisfies EducationalModule[];
